"""
GitHub Releases cache — extracted 1-for-1 from app.py.
Reads GITHUB_REPO and GITHUB_TOKEN from environment variables.
"""
import io
import json
import os
from datetime import datetime
from typing import Callable, Dict, Optional, Tuple

import pandas as pd
import requests

from .helpers import _coerce_df_for_parquet

_GH_API             = "https://api.github.com"
_CACHE_RELEASE_TAG  = "data-cache"
_CACHE_MANIFEST_NAME = "_manifest.json"
_CACHE_FILES = {
    "sales_df":    "sales_df.parquet",
    "mtr_df":      "mtr_df.parquet",
    "meesho_df":   "meesho_df.parquet",
    "myntra_df":   "myntra_df.parquet",
    "flipkart_df": "flipkart_df.parquet",
    "snapdeal_df": "snapdeal_df.parquet",
    "sku_mapping": "sku_mapping.json",
}


def _gh_headers() -> Optional[Dict[str, str]]:
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        return None
    return {
        "Authorization": f"token {token}",
        "Accept":        "application/vnd.github+json",
    }


def _gh_repo() -> Optional[str]:
    return os.environ.get("GITHUB_REPO")


def _get_gh_release() -> Tuple[Optional[int], Dict, Optional[str]]:
    """Get or create the data-cache release. Returns (release_id, assets_dict, error)."""
    headers = _gh_headers()
    repo    = _gh_repo()
    if not headers or not repo:
        return None, {}, "GitHub secrets not configured (set GITHUB_TOKEN + GITHUB_REPO env vars)"
    try:
        r = requests.get(
            f"{_GH_API}/repos/{repo}/releases/tags/{_CACHE_RELEASE_TAG}",
            headers=headers, timeout=15,
        )
        if r.status_code == 200:
            rel    = r.json()
            assets = {a["name"]: (a["id"], a["browser_download_url"]) for a in rel.get("assets", [])}
            return rel["id"], assets, None
        # Create release
        r = requests.post(
            f"{_GH_API}/repos/{repo}/releases",
            headers=headers,
            json={
                "tag_name":   _CACHE_RELEASE_TAG,
                "name":       "Data Cache",
                "body":       "Auto-generated by Yash Gallery ERP",
                "prerelease": True,
            },
            timeout=15,
        )
        r.raise_for_status()
        return r.json()["id"], {}, None
    except Exception as e:
        return None, {}, str(e)


def _gh_delete_asset(asset_id: int) -> None:
    repo    = _gh_repo()
    headers = _gh_headers()
    if not repo or not headers:
        return
    requests.delete(f"{_GH_API}/repos/{repo}/releases/assets/{asset_id}",
                    headers=headers, timeout=15)


def _gh_upload_asset(
    release_id: int, filename: str, data: bytes, existing_id: Optional[int] = None
) -> None:
    repo    = _gh_repo()
    headers = _gh_headers()
    if not repo or not headers:
        raise RuntimeError("GitHub not configured")
    if existing_id:
        _gh_delete_asset(existing_id)
    upload_url = f"https://uploads.github.com/repos/{repo}/releases/{release_id}/assets"
    upload_headers = {**headers, "Content-Type": "application/octet-stream"}
    r = requests.post(
        upload_url, headers=upload_headers,
        params={"name": filename}, data=data, timeout=300,
    )
    r.raise_for_status()


def _gh_download_asset(url: str) -> bytes:
    headers = _gh_headers() or {}
    headers["Accept"] = "application/octet-stream"
    r = requests.get(url, headers=headers, timeout=300)
    r.raise_for_status()
    return r.content


def save_cache_to_drive(
    session_data: dict,
    progress_callback: Optional[Callable] = None,
) -> Tuple[bool, str]:
    """
    Upload session DataFrames/dicts to GitHub Release assets.
    session_data: dict with keys matching _CACHE_FILES (e.g. "sales_df", "mtr_df", ...).
    """
    release_id, assets, err = _get_gh_release()
    if err:
        return False, f"GitHub not configured: {err}"

    manifest = {
        "saved_at":         datetime.utcnow().isoformat(timespec="seconds"),
        "saved_at_display": datetime.now().strftime("%d %b %Y, %I:%M %p"),
        "files":            {},
        "row_counts":       {},
    }
    items = list(_CACHE_FILES.items())
    total = len(items) + 1

    for step, (ss_key, filename) in enumerate(items):
        if progress_callback:
            progress_callback(step, total, f"Uploading {filename}…")
        data_obj = session_data.get(ss_key)
        if data_obj is None:
            continue
        try:
            if isinstance(data_obj, pd.DataFrame):
                if data_obj.empty:
                    continue
                buf = io.BytesIO()
                _coerce_df_for_parquet(data_obj).to_parquet(
                    buf, index=False, engine="pyarrow", compression="snappy"
                )
                file_bytes = buf.getvalue()
                manifest["row_counts"][ss_key] = len(data_obj)
            elif isinstance(data_obj, dict):
                file_bytes = json.dumps(data_obj, ensure_ascii=False).encode("utf-8")
                manifest["row_counts"][ss_key] = len(data_obj)
            else:
                continue
            existing_id = assets.get(filename, (None,))[0]
            _gh_upload_asset(release_id, filename, file_bytes, existing_id)
            manifest["files"][filename] = filename
        except Exception as e:
            return False, f"Failed uploading {filename}: {e}"

    if progress_callback:
        progress_callback(total - 1, total, "Writing manifest…")
    try:
        manifest_bytes = json.dumps(manifest, ensure_ascii=False, indent=2).encode("utf-8")
        existing_id    = assets.get(_CACHE_MANIFEST_NAME, (None,))[0]
        _gh_upload_asset(release_id, _CACHE_MANIFEST_NAME, manifest_bytes, existing_id)
    except Exception as e:
        return False, f"Failed writing manifest: {e}"

    return True, f"Saved {len(manifest['files'])} files ({manifest['saved_at_display']})."


def load_cache_from_drive(
    progress_callback: Optional[Callable] = None,
) -> Tuple[bool, str, dict]:
    """
    Download parquet/JSON assets from GitHub Release.
    Returns (ok, message, loaded_data_dict).
    """
    _, assets, err = _get_gh_release()
    if err:
        return False, f"GitHub not configured: {err}", {}
    if _CACHE_MANIFEST_NAME not in assets:
        return False, "No cache found. Run Load All Data first.", {}
    try:
        raw      = _gh_download_asset(assets[_CACHE_MANIFEST_NAME][1])
        manifest = json.loads(raw.decode("utf-8"))
    except Exception as e:
        return False, f"Could not read manifest: {e}", {}

    items      = list(_CACHE_FILES.items())
    loaded     = {}
    for step, (ss_key, filename) in enumerate(items):
        if progress_callback:
            progress_callback(step, len(items), f"Downloading {filename}…")
        if filename not in assets:
            continue
        try:
            raw = _gh_download_asset(assets[filename][1])
            if filename.endswith(".parquet"):
                loaded[ss_key] = pd.read_parquet(io.BytesIO(raw), engine="pyarrow")
            elif filename.endswith(".json"):
                loaded[ss_key] = json.loads(raw.decode("utf-8"))
        except Exception as e:
            return False, f"Failed loading {filename}: {e}", {}

    if not loaded:
        return False, "Cache was empty. Run Load All Data first.", {}

    row_counts = manifest.get("row_counts", {})
    summary    = ", ".join(
        f"{k}: {row_counts[k]:,} rows"
        for k in loaded
        if k != "sku_mapping" and k in row_counts
    )
    msg = f"Loaded from GitHub ({manifest.get('saved_at_display', '?')}). {summary}."
    return True, msg, loaded


def load_sku_mapping_from_drive() -> dict:
    """
    Download only sku_mapping.json from GitHub releases.
    Fast — avoids loading all parquet DataFrames.
    Returns empty dict if GitHub is not configured or asset is missing.
    """
    try:
        _, assets, err = _get_gh_release()
        if err or "sku_mapping.json" not in assets:
            return {}
        raw = _gh_download_asset(assets["sku_mapping.json"][1])
        return json.loads(raw.decode("utf-8"))
    except Exception:
        return {}


def get_cache_manifest() -> Optional[dict]:
    """Return the manifest JSON if a cache exists, else None."""
    _, assets, err = _get_gh_release()
    if err or _CACHE_MANIFEST_NAME not in assets:
        return None
    try:
        raw = _gh_download_asset(assets[_CACHE_MANIFEST_NAME][1])
        return json.loads(raw.decode("utf-8"))
    except Exception:
        return None
